### ISSUE TITLE
コンテンツを保存する

### ISSUE THREAD

**Issue by ghost** [halcyon-org/kizuna#115]
S3もといCloud Storageに突っ込む
S3互換なのでS3系のSDKでok

`{{Koyo Id}}/`みたいなプレフィックスで、`{{Koyo Data Id}}.json`みたいなでかいJSONを作る
スキーマは
```
id: {{koyo id}}
values:
 - point:
    lat:
    lng:
   value:
   optioanl:
    key: value
    key2: value2
...
```
